name = 'ihappystories'
main = "src/worker.ts"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]

routes = [
  { pattern = "stories.umaibo.dev", custom_domain = true }
]

[site]
bucket = "./dist"

[[queues.producers]]
binding = "AUDIO_QUEUE"
queue = "monogatari-audio-queue"

[[queues.consumers]]
queue = "monogatari-audio-queue"
