name = 'monogatari'
main = "src/worker.ts"
compatibility_date = "2024-04-05"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

routes = [
  { pattern = "monogatari.umaibo.dev", custom_domain = true }
]

[vars]
SUPABASE_URL = "YOUR_SUPABASE_URL"
SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY" 
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"