name = 'monogatari'
main = "src/worker.ts"
compatibility_date = "2024-04-05"

routes = [
  { pattern = "monogatari.umaibo.dev", custom_domain = true }
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
