name = 'monogatari'
main = "src/worker.ts"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]

routes = [
  { pattern = "stories.umaibo.dev", custom_domain = true }
]

[site]
bucket = "./dist"
